Refactor project setup + update to RN 68.2 + update dev dependencies
lottie-react-native/lottie-react-native pull request #878
Opened 2022-05-19 04:43 UTC by AlexanderEggers

This PR bases on https://github.com/lottie-react-native/lottie-react-native/pull/877 but includes a decent amount of additional changes to make the project better aligned to the rest of open source libraries out there. These changes are needed so that I can have two fully different example projects: one for fabric and one without fabric.

### Summary of the breaking setup changes
- The new setup has two fully separated areas: lib (root) and example
- The lib is the root folder (as before) which takes care of actually containing the lib source code and building the lib files via babel.
- The example is fully separated from the lib and only has a "weak" reference to that one via `"lottie-react-native": "file:.."`. That allows us to build multiple example projects without having to deal with the additional complexity in the root folder which should just take care of the lib creation.
    - Because of these changes I was able to simplify the examples quite a lot and make them a lot closer to how this library will be used in a final project.
    - Android can finally use `npx react-native ...` to be compiled instead of the strange previous way.
- Remove npm offline usage. That is causing some problems with the new setup.
 
### Testing
- [x] Android
- [x] iOS
- [ ] Windows - I need help with that. I don't have a Windows setup for this.

### Additionally this PR includes some project specific changes
- Using the RN 0.68.2 [upgrade helper ](https://react-native-community.github.io/upgrade-helper/)to make changes to the whole project.
- Update dev dependencies - there were plenty which were extremely outdated and I have not noticed any issues so far. Please correct me if I missed something. I am happy to revert some of these dependency updates.
- Allow ndkVersion to be injected from the consumer base project. That is needed because M1/non-M1 machine are needing to use different ndk versions.

### Missing setup changes and known issues
- More example project work which contains simple build script cleanup.
- When using the example, you need to ensure that the root folder does **not** have a node_modules folder. If that is the case, react native will not be able to correctly display the lottie native view. So you need to run yarn install in the root, have the lib folder updated, remove node_modules, remove node_modules in the example project and run yarn install there again. That can be managed and is just a few steps but something which can ideally be automated.

### Next
With having a better project setup, I would start adding the actual RN new architecture code as part of the next PR.

### Note for the upcoming new architecture work
@emilioicai I am planning to build a new fabric example project which is just showing a single lottie animation for the MVP.

2022-06-28 07:41 UTC, Willham12 commented
@AlexanderEggers thanks for the contribution, are there any news on this PR?

2022-06-28 10:41 UTC, AlexanderEggers commented
@Willham12 I am still waiting for feedback by @emilioicai  for this PR and I need help to verify if the publishing and thd windows version are still working fine.

2022-06-28 10:44 UTC, AlexanderEggers commented
@emilioicai Can we merge this PR prior to any additional changes to develop? Otherwise the changes are going to be extremely difficult for me to maintain. I noticed that you merged some changes which require a rebase from my side now. I will try to take care of that some time tomorrow.

2022-07-12 12:33 UTC, emilioicai commented
Hey Alex, yes, sorry for not being  that active, these weeks have been quite hectic for me. I started reviewing and hopefully merge before the week ends. I promise I won't commit any large changes into the repo before this PR is merged

2022-07-23 11:41 UTC, matinzd commented
It seems that there are some merge conflicts @AlexanderEggers. Can you fix them?

2022-07-27 19:21 UTC, matinzd commented
Isn’t it better to upgrade to 0.69.3. It has been a while that this PR is still open.

2022-07-27 22:58 UTC, AlexanderEggers commented
> 

At some stage, yes. But I want to avoid to keep updating this PR and just have a base ready for now.

2022-07-29 16:44 UTC, matinzd requested changes
Thank you for your pull request and this is a huge step for the future of the repo. So happy to see `those npm-packages-offline-cache` are all removed.
It seems like example app for both Android and iOS is not working after fixing the build myself. 
```
 ERROR  Invariant Violation: View config getter callback for component `LottieAnimationView` must be a function (received `undefined`).

This error is located at:
    in LottieAnimationView (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at LottieView.js:178)
    in RCTView (at View.js:32)
    in View (at LottieView.js:177)
    in LottieView (at LottieAnimatedExample.js:170)
    in RCTView (at View.js:32)
    in View (at LottieAnimatedExample.js:169)
    in RCTView (at View.js:32)
    in View (at LottieAnimatedExample.js:163)
    in LottieAnimatedExample (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in example(RootComponent) (at renderApplication.js:60)
```

I also added some other comments up there. 

**UPDATE:** 
I found the issue with the example app. Module's`node_modules` folder should not get included inside example's `node_modules` causing confusion between peer dependencies. After removing inner `node_modules` folder app started working both on android and iOS. 
It seems like metro config should be fixed to blacklist inner `node_modules` inside installed project.

- example
   - node_modules
      - lottie-react-native
          - node_modules <-- this should be ignored

2022-07-29 16:44 UTC, matinzd commented on lottie-react-native.podspec
>    s.source       = { :git => "https://github.com/react-community/lottie-react-native.git", :tag => "v#{s.version}" }
This needs to be updated to: `https://github.com/lottie-react-native/lottie-react-native.git`

2022-07-29 17:33 UTC, matinzd commented on example/metro.config.js
> +};
I would suggest this metro config for example app.

```suggestion
const path = require('path');
const exclusionList = require('metro-config/src/defaults/exclusionList');
const escape = require('escape-string-regexp');
const pack = require('../package.json');

const root = path.resolve(__dirname, '..');

const modules = [...Object.keys(pack.peerDependencies)];

module.exports = {
  projectRoot: __dirname,
  watchFolders: [root],

  // We need to make sure that only one version is loaded for peerDependencies
  // So we exclude them at the root, and alias them to the versions in example's node_modules
  resolver: {
    blacklistRE: exclusionList(
      modules.map(
        m => new RegExp(`^${escape(path.join(root, 'node_modules', m))}\\/.*$`),
      ),
    ),

    extraNodeModules: modules.reduce((acc, name) => {
      acc[name] = path.join(__dirname, 'node_modules', name);
      return acc;
    }, {}),
  },

  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```

2022-07-30 21:49 UTC, matinzd commented
You can just pick this commit if you don't want to put time into fixing the comments. 
https://github.com/lottie-react-native/lottie-react-native/commit/aa10ae3040f7a02f1a6fcfa7a98e53962c553403

2022-08-02 09:32 UTC, AlexanderEggers commented
@matinzd Thanks for doing the review. I will try to have a look at your comments by the end of this week.

2022-08-03 06:51 UTC, AlexanderEggers commented
@matinzd Thanks again for the review. I cherry-picked your commit into this branch and added a few minor additional changes. Let me know if you can notice anything else.

2022-08-03 07:04 UTC, matinzd commented
> @matinzd Thanks again for the review. I cherry-picked your commit into this branch and added a few minor additional changes. Let me know if you can notice anything else.

I am going to test windows today on my wife’s latpop and setup the environment 😅.

2022-08-03 10:01 UTC, AlexanderEggers commented
@emilioicai @matinzd I started working on the fabric support. I think it would be great if we can get this first part either merged into `/master` or we create a `/fabric` branch which we will use internally for now until it is stable enough for the public. What do you think?

The relevant work is currently sitting in this branch: https://github.com/AlexanderEggers/lottie-react-native/tree/feature/add-fabric-support I haven't had a chance to work much on that. I just migrated the android and JS code to technically support fabric but I am having troubles running the non-fabric example project at the moment.

Let me know how you want to proceed with this PR and the future fabric work.

2022-08-03 10:06 UTC, matinzd commented
> @emilioicai @matinzd I started working on the fabric support. I think it would be great if we can get this first part either merged into `/master` or we create a `/fabric` branch which we will use internally for now until it is stable enough for the public. What do you think?
> 
> The relevant work is currently sitting in this branch: https://github.com/AlexanderEggers/lottie-react-native/tree/feature/add-fabric-support I haven't had a chance to work much on that. I just migrated the android and JS code to technically support fabric but I am having troubles running the non-fabric example project at the moment.
> 
> Let me know how you want to proceed with this PR and the future fabric work.

That would be great! We also need to start working on fabric and make it backward compatible. There is a repo in react native community with examples for making fabric backward compatible, so we can use that. 

https://github.com/cipolleschi/RNNewArchitectureLibraries/tree/feat/back-fabric-component-070

2022-08-03 12:45 UTC, AlexanderEggers commented
@matinzd Yep I'm using that one 👍 Can you create a `/fabric` branch based on master so that I can retarget this PR?

2022-08-03 21:10 UTC, emilioicai commented
@matinzd I finally managed to have the windows support tested and everything looks good on that front 🙌 
@AlexanderEggers I created that [fabric branch](https://github.com/lottie-react-native/lottie-react-native/tree/fabric) for you to target, thanks again for your support!

2022-08-03 23:16 UTC, AlexanderEggers commented
@emilioicai Thanks for creating the branch. I re-targeted the branch to that branch now. I think the only remaining thing we need to verify is the NPM deployment but we could also do that when we closer to the actual going public, what do you think?

2022-08-04 05:23 UTC, matinzd commented
@emilioicai 
Where are we going to release v6 if we are targeting this on fabric branch?

2022-08-04 05:28 UTC, matinzd approved these changes

2022-08-04 05:31 UTC, AlexanderEggers commented
> About NPM deployment we can start with `lottie-react-native@next` for /fabric branch?

I think that's a great idea 👍

2022-08-04 19:40 UTC, matinzd commented
Let's change base branch to master again so that @emilioicai can release the latest changes as a patch. Then we can start `fabric` branch based on master. @AlexanderEggers

2022-08-04 23:54 UTC, AlexanderEggers commented
@emilioicai Would it be possible if we can get this PR merged into `/fabric` this weekend? I'm pretty close with the android fabric work and got actually plenty of notes that we need to discuss together.

2022-08-05 13:38 UTC, emilioicai approved these changes

2022-08-05 13:38 UTC, merged